newdjango/client/urls.py
"""Client URL Configuration."""

from django.urls import path
from .views import (HomePageTemplateView,
                    PersonListView,
                    PersonCreateView,
                    PersonUpdateView,
                    PersonDetailView,
                    PersonDeleteView)

app_name = "client"


urlpatterns = [
    path('', HomePageTemplateView.as_view(), name="home"),
    path('person/list/', PersonListView.as_view(), name="list-person"),
    path('person/create/', PersonCreateView.as_view(), name="create-person"),
    path('person/update/<pk>/', PersonUpdateView.as_view(), name="update-person"),
    path('person/<pk>/', PersonDetailView.as_view(), name="detail-person"),
    path('person/<pk>/delete/', PersonDeleteView.as_view(), name="delete-person")
]

newdjango/newdjango/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newdjango/client/models.py
"""Client models."""

from django.db import models
from django.urls import reverse


class Person(models.Model):
    """Person model."""

    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=100)

    age = models.IntegerField(default=16)
    id_number = models.CharField(max_length=13, default=None, help_text="RSA ID number")
    is_first_user = models.BooleanField(default=False,
                                        help_text="Is this your\
        first time using the system?")

    contact_number = models.CharField(max_length=250,
                                      default=None,
                                      null=True,
                                      blank=True)
    GROUP_NAMES = ((0, 'Group 1'),
                   (1, 'Group 2'),
                   (2, 'Group 3'))
    group = models.IntegerField(default=0, choices=GROUP_NAMES)

    profile_pic = models.ImageField(upload_to="person/profile_pics/",
                                    default=None,
                                    null=True,
                                    blank=True)

    timestamp = models.DateTimeField(auto_now_add=True)
    timestamp_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """To string function."""
        return "{} {}".format(self.first_name, self.last_name)

    def get_absolute_url(self):
        """Return to a url after inserting."""
        return reverse('client:list-person', kwargs={})


class Car(models.Model):
    """Car class that belongs to person."""

    person = models.ForeignKey(Person, on_delete=models.CASCADE)

    vin_number = models.CharField(max_length=250)
    engine_number = models.CharField(max_length=250)

    timestamp = models.DateTimeField(auto_now_add=True)
    timestamp_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """To string function."""
        return "{} {}".format(self.person, self.engine_number)

newdjango/register/models.py
"""Register models."""

from django.db import models
from client.models import (Person)


class Attendance(models.Model):
    """Atttendance model."""

    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    checkin_time = models.DateTimeField(null=True,
                                        blank=True,
                                        default=None)
    checkout_time = models.DateTimeField(null=True,
                                         blank=True,
                                         default=None)

    comment = models.TextField(max_length=2500,
                               default=None,
                               blank=True,
                               null=True,
                               help_text="Add in an optional comment")

    timestamp_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """To string model."""
        return "{}".format(self.person, self.checkin_time)

newdjango/client/views.py
"""Client view classes."""
from django.urls import reverse_lazy
from django.views.generic import (TemplateView,
                                  ListView,
                                  DetailView)
from django.views.generic.edit import (CreateView,
                                       UpdateView,
                                       DeleteView)
from .models import (Person)


class HomePageTemplateView(TemplateView):
    """Home page templateview."""

    template_name = 'client/homepage.html'


class PersonListView(ListView):
    """Person list view."""

    model = Person


class PersonCreateView(CreateView):
    """Person create view."""

    model = Person
    fields = ['first_name',
              'last_name',
              'id_number']


class PersonUpdateView(UpdateView):
    """Person update view."""

    model = Person
    fields = ['first_name',
              'age',
              'is_first_user',
              'group',
              'last_name',
              'profile_pic']


class PersonDetailView(DetailView):
    """Person detail view."""

    model = Person


class PersonDeleteView(DeleteView):
    """Person delete view."""

    model = Person
    success_url = reverse_lazy('client:list-person')

newdjango/register/views.py
from django.shortcuts import render

# Create your views here.

newdjango/client/templates/client/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <!-- bootstrap js-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- end of bootstrap js-->
</body>
</html>

newdjango/client/templates/client/form_template.html
{% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}

newdjango/client/templates/client/homepage.html
{% extends 'client/base.html' %}

{% block title %}
Main Menu
{% endblock %}

{% block body %}
<h1>Main menu</h1>
<ul class="list-group">
    <li class="list-group-item">
        <a class="btn btn-outline-primary btn-sm" href="{% url 'client:list-person' %}">Persons</a>
    </li>
    <li class="list-group-item">
        Houses
    </li>
    <li class="list-group-item">
        Cars
    </li>
    <li class="list-group-item">
        Food
    </li>
</ul>
{% endblock %}

newdjango/client/templates/client/person_confirm_delete.html
{% extends 'client/base.html' %}


{% block title %}
Confirm Deletion
{% endblock %}

{% block body %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="btn btn-danger" type="submit" value="Confirm">
    <a class="btn btn-outline-primary" href="{% url 'client:list-person' %}">Cancel</a>
</form>
{% endblock %}

newdjango/client/templates/client/person_detail.html
{% extends 'client/base.html' %}

{% block title %}
Hello {{object}} 
{% endblock %}

{% block body %}
<br>
<a class="btn btn-outline-primary btn-sm" href="{% url 'client:list-person' %}">Back</a>
<br>
<br>
<div class="container">

    <div class="card text-center">
      <div class="card-header">
        Welcome
    </div>
    <div class="card-body">
        {% if object.profile_pic %}
        <img src="{{ object.profile_pic.url }}" class="card-img-top" alt="{{ object }}">
        {% endif %}
        <h5 class="card-title">
            {{object.first_name|title}} {{ object.last_name|title }}
        </h5>
        <p class="card-text">
            Age: {{ object.age }}
            <br>
            ID Number: {{ object.id_number }}
            <br>
            <b>Bio:</b>
            <br>
            {% lorem %}
        </p>
        <a href="{% url 'client:update-person' object.id %}" class="btn btn-primary">edit</a>
    </div>
    <div class="card-footer text-muted">
        {{ object.timestamp_updated }}
    </div>
</div>
</div>
{% endblock %}

newdjango/client/templates/client/person_form.html
{% extends 'client/base.html' %}

{% block title %}
Register a new person
{% endblock %}

{% block body %}
<h2>Register a new person</h2>

<form method="post" enctype="multipart/form-data">
    {% include 'client/form_template.html' %}
    {% csrf_token %}
    <button type="submit">Save</button>
</form>
{% endblock %}

newdjango/client/templates/client/person_list.html
{% extends 'client/base.html' %}

{% block title %}
List of People ({{ object_list|length }})
{% endblock %}

{% block body %}
<br>
<a class="btn btn-outline-primary btn-sm" href="{% url 'client:home' %}"> Home </a>
<a class="btn btn-outline-primary btn-sm" href="{% url 'client:create-person' %}"> Create Person </a> 
<br>
<br>
{% if object_list|length > 0 %}
<ul class="list-group">
    {% for person in object_list %}
    <li class="list-group-item">
        <a class="btn btn-outline-dark btn-sm" href="{% url 'client:detail-person' person.id %}">{{ person.first_name }} </a>
        <a class="btn btn-dark float-right btn-sm" href="{% url 'client:update-person' person.id %}">edit</a> 
        <a class="btn btn-danger float-right btn-sm" style="margin-right:10px" href="{% url 'client:delete-person' person.id %}">delete</a> 
    </li>
    {% endfor %}
</ul>
{% else %}
<b>No Records, yet.</b>
{% endif %}
{% endblock %}